### ISSUE TITLE
Extend the continuous integration process to deploy the app on Heroku

### ISSUE THREAD

**Issue by rouvoy** [Oupsla/BtrShop-cloud#10]
Whenever TravisCI succeeds to build the project, it should deploy it automatically on Heroku.

**Comment by Oupsla** [comment]
Heroku detects and deploys automatically when a new commit is made on master (so when a new Pr is merged)
Do you want to change this pipeline and make Travis doing the push to Heroku ?

**Comment by Oupsla** [comment]
And Heroku also checks if the CI (Travis here) is ok with the merge before deploying

**Comment by rouvoy** [comment]
As long as the deployment checks that the current version succeeds to compile and test in Travis in order to be sure that the online version works correctly, I'm fine.
