### ISSUE TITLE
Add more tests to cover potential errors

### ISSUE THREAD

**Issue by rouvoy** [Oupsla/BtrShop-cloud#7]
The tests should not only focus on simple scenarios that works, but also cover potential error (_e.g._, incorrect EAN) to be sure that the service will not crash in such situations.

**Comment by Oupsla** [comment]
I have added some tests and express-validator module to validate parameters sent in query

Tell me if this is enough for the first mvp

I have also remove routes that is not used at this moment (create/update/...)
